### ISSUE TITLE
verse

### ISSUE THREAD

**Issue by DanKrizzy** [jackson-nestelroad/christ-centered-2.0#1] opened 2024-03-07 07:30 UTC
same verse for about 4 days

**Comment by jackson-nestelroad** [comment] 2024-03-07 14:35
Thanks for reaching out!!

Could you please provide some more context to help debug or reproduce this?

1. What verse is displaying?
2. Can you double check that the “Bible Verse” option in the left-hand side menu is empty? This option is used to show a custom verse and won’t ever automatically unset. 
3. Could you check if there are any errors in the Chrome DevTools Console when you open the app? You can screenshot or paste whatever is logged there. This will be the biggest help. 

Thank you!

**Comment by jackson-nestelroad** [comment] 2024-03-30 22:10
Closing this since there is no way to reproduce. Please feel free to reopen if you have steps to reproduce. Thank you!

**Closed as completed by jackson-nestelroad** 2024-03-30 22:10 UTC
Labels: bug
